### ISSUE TITLE
Update verror dep

### ISSUE THREAD

**Issue by coreyfarrell** [joyent/node-jsprim#21]
It appears the VError constructor has remained the same between verror@1.3.6 and verror@1.10.0.  Could you update the dependency for this module?  I can submit a PR if wanted.

**Comment by davepacheco** [comment]
Why?  Are you having multiple versions pulled in needlessly?

**Comment by coreyfarrell** [comment]
No, just identifying outdated dependencies that can be updated without breakage.

**Comment by davepacheco** [comment]
Fixed and published in v1.4.1.
