### ISSUE TITLE
Update extsprintf dependency

### ISSUE THREAD

**Issue by danielbprice** [joyent/node-jsprim#22]
My build system is presently stuck behind a firewall, the misconfiguration of which is making it hard to get to github.  We have a caching NPM proxy, which works well, and all of the modules we use during the build are presently cached.  However, when `node-jsprim` pulls in a relatively old version of `extsprintf` (1.0.2), the `git submodules` initialization fails for git://github.com/... URIs.  Those git submodules were removed from extsprintf in commit [76e9d14be8d6a jsPrintf dicey use of arguments](https://github.com/davepacheco/node-extsprintf/commit/76e9d14be8d6abb743be795e498d0448c4f7eea2).  So updating the dependency would help us out in this (admittedly fringe) case.

I'm filing this issue and will followup with a PR to resolve it along with #21.

Happy to take guidance on other solutions, but this seemed to me to make sense.

**Comment by davepacheco** [comment]
Sure!

This repo uses a different contribution process now, but that was never updated in the README or a contributing file.  I'll put together a change for this issue, #21, and to update the contribution guidelines.

**Comment by davepacheco** [comment]
Proposed change: https://cr.joyent.us/#/c/2317/1

This is `make prepush` clean.

**Comment by davepacheco** [comment]
Published in v1.4.1.
