### ISSUE TITLE
depends on vulnarable json-schema version

### ISSUE THREAD

**Issue by kacperpll** [joyent/node-jsprim#36]
Hey,

please bump the dependency request to not have the transient dependency on vulnerable json-schema < 0.4.0.

Thank you!

json-schema  <0.4.0
Severity: critical
json-schema is vulnerable to Prototype Pollution - https://github.com/advisories/GHSA-896r-f27r-55mw

node_modules/npm/node_modules/json-schema
  jsprim  0.3.0 - 1.4.1 || 2.0.0 - 2.0.1
  Depends on vulnerable versions of json-schema
  node_modules/npm/node_modules/jsprim

**Comment by trivikr** [comment]
This issue can be resolved, as jsprim versions 1.4.2 and 2.0.2 depend on json-schema@0.4.0

Source code:
* https://github.com/TritonDataCenter/node-jsprim/blob/5c8475fd44567e459b1b73b82f2669c39a0642b8/package.json#L13
* https://github.com/TritonDataCenter/node-jsprim/blob/017f74473e55872cf71113bec35ce46de74fbe17/package.json#L13
